name: Build Devuan Live ISO

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-iso:
    runs-on: ubuntu-24.04
    container:
      image: debian:latest
      volumes:
        - /proc:/proc
      options: --privileged --security-opt seccomp=unconfined
    name: Devuan Live ISO Build
    steps:
      - name: Install dependencies
        run: |
          apt update
          apt install -y git sudo live-build curl debootstrap wget

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Devuan environment
        run: |
          # Create symlink for excalibur to use sid script
          ln -sf sid /usr/share/debootstrap/scripts/excalibur
          # Install Devuan keyring
          cd /tmp
          wget http://pkgmaster.devuan.org/devuan/pool/main/d/devuan-keyring/devuan-keyring_2025.08.09_all.deb
          dpkg -i devuan-keyring_2025.08.09_all.deb || apt-get install -y -f
          cd -

      - name: Configure live-build
        run: |
          lb config

      - name: Build the ISO
        run: |
          lb build
          iso_file=$(ls *.iso | head -n 1)
          date_str=$(date +%Y.%m.%d)
          mv "$iso_file" "devuan-live-${date_str}-amd64.iso"

      - name: Upload files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          ls -lh *.iso
          wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
          bash upload.sh *.iso
